sylius_twig_hooks:
    hooks:
        sylius_admin.product_variant.update.content:
            form:
                component: 'umanit:product_variant:form'

        sylius_admin.product_variant.update.content.form.side_navigation:
            attributes:
                template: '@SyliusAdmin/product/form/side_navigation/attributes.html.twig'

        sylius_admin.product_variant.update.content.form.sections:
            attributes:
                template: '@SyliusAdmin/product/form/sections/attributes.html.twig'

        sylius_admin.product_variant.update.content.form.sections.attributes:
            autocomplete:
                template: '@SyliusAdmin/product/form/sections/attributes/autocomplete.html.twig'
                priority: 100
            list:
                template: '@SyliusAdmin/product/form/sections/attributes/list.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.autocomplete:
            input:
                template: '@UmanitSyliusProductVariantAttributePlugin/product_variant/form/sections/attributes/autocomplete/input.html.twig'
                priority: 100
            button:
                template: '@SyliusAdmin/product/form/sections/attributes/autocomplete/button.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.list:
            item:
                template: '@SyliusAdmin/product/form/sections/attributes/list/item.html.twig'
                priority: 100
            translations:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.list.item:
            label:
                template: '@SyliusAdmin/product/form/sections/attributes/list/item/label.html.twig'
                priority: 100
            remove_button:
                template: '@SyliusAdmin/product/form/sections/attributes/list/item/remove_button.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.list.translations:
            field:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.list.translations.field:
            language:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/language.html.twig'
                priority: 200
            label:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/label.html.twig'
                priority: 100
            input:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/input_group.html.twig'
                priority: 0

        sylius_admin.product_variant.update.content.form.sections.attributes.list.translations.field.input_group:
            widget:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/input_group/widget.html.twig'
                priority: 200
            button:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/input_group/apply_to_all.html.twig'
                priority: 100
            errors:
                template: '@SyliusAdmin/product/form/sections/attributes/list/translations/field/input_group/errors.html.twig'
                priority: 0
