imports:
    - { resource: 'packages/doctrine.yaml' }
    - { resource: '@UmanitSyliusProductVariantAttributePlugin/Resources/config/sylius_grid.yaml' }
    - { resource: '@UmanitSyliusProductVariantAttributePlugin/Resources/config/sylius_twig_hooks/product_variant_attribute_create.yaml' }
    - { resource: '@UmanitSyliusProductVariantAttributePlugin/Resources/config/sylius_twig_hooks/product_variant_attribute_update.yaml' }
    - { resource: '@UmanitSyliusProductVariantAttributePlugin/Resources/config/sylius_twig_hooks/product_variant_create.yaml' }
    - { resource: '@UmanitSyliusProductVariantAttributePlugin/Resources/config/sylius_twig_hooks/product_variant_update.yaml' }
